//login
const REGISTER_POST_SUCCESS = "register/postSuccess";
const LOGIN_POST_SUCCESS = "login/postSuccess";

// fetch repo
const FETCH_REPOS_REQUEST = "FETCH_REPOS_REQUEST";
const FETCH_REPOS_SUCCESS = "FETCH_REPOS_SUCCESS";
const FETCH_REPOS_FAILURE = "FETCH_REPOS_FAILURE";

// add repo
const ADD_REPO_SUCCESS = "ADD_REPO_SUCCESS";
const ADD_REPO_FAILURE = "ADD_REPO_FAILURE";

// fetch task
const GET_TASKS_REQUEST = "GET_TASKS_REQUEST";
const GET_TASKS_SUCCESS = "GET_TASKS_SUCCESS";
const GET_TASKS_FAILURE = "GET_TASKS_FAILURE";

// add task
const ADD_TASK_SUCCESS = "ADD_TASK_SUCCESS";

// fetch search container
const FETCH_SEARCH_CONTAINER = "SEARCH_CONTAINER_SUCCESS";

// add files
const ADD_FILES_SUCCESS = "ADD_FILES_SUCCESS";

// fetch task detail
const FETCH_TASK_DETAIL_SUCCESS = "FETCH_TASK_DETAIL_SUCCESS";
const FETCH_TASK_LOGS_SUCCESS = "FETCH_TASK_LOGS_SUCCESS";

// delete repo
const DELETE_REPO_SUCCESS = "DELETE_REPO_SUCCESS";
const DELETE_REPO_FAILURE = "DELETE_REPO_FAILURE";

// delete task
const DELETE_TASK_SUCCESS = "DELETE_TASK_SUCCESS";
const DELETE_TASK_FAILURE = "DELETE_TASK_FAILURE";


export {
  REGISTER_POST_SUCCESS,
  LOGIN_POST_SUCCESS,
  FETCH_REPOS_REQUEST,
  FETCH_REPOS_SUCCESS,
  FETCH_REPOS_FAILURE,
  ADD_REPO_SUCCESS,
  ADD_REPO_FAILURE,
  GET_TASKS_REQUEST,
  GET_TASKS_SUCCESS,
  GET_TASKS_FAILURE,
  ADD_TASK_SUCCESS,
  FETCH_SEARCH_CONTAINER,
  ADD_FILES_SUCCESS,
  FETCH_TASK_DETAIL_SUCCESS,
  FETCH_TASK_LOGS_SUCCESS,
  DELETE_REPO_SUCCESS,
  DELETE_REPO_FAILURE,
  DELETE_TASK_SUCCESS,
  DELETE_TASK_FAILURE
};
